name: Tests

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      uses: getsentry/action-setup-venv@v2
      with:
        python-version: ${{ matrix.python-version }}
        system-site-packages: false
        cache-dependency-path: |
          requirements.txt
        install-cmd: |
          pip install -r requirements.txt
          pip install -e . --no-deps --force-reinstall
    
    - name: Run tests
      run: |
        python3 -m unittest
